apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app-sites
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Valery00781/gitops-proto.git
        revision: main
        files:
          - path: "sites/*.json"
  template:
    metadata:
      name: "demo-app-{{site}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Valery00781/gitops-proto.git
        targetRevision: main
        path: demo-app-chart
        helm:
          valueFiles:
            - "{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{site}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
